id: I51EA6051
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T03:20:08+00:00'
last_modified: '2022-06-08T14:11:15.793855+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD95727
  title: གངས་ལྗོངས་རིག་བཅུའི་སྙིང་བཅུད་ཆེན་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '8460':
      image_group_id: I2PD16000
      title: ''
      total_pages: 2076
      order: 1
      base_file: 8460.txt
    9BD9:
      image_group_id: I2PD16001
      title: ''
      total_pages: 1962
      order: 2
      base_file: 9BD9.txt
    0C22:
      image_group_id: I2PD16002
      title: ''
      total_pages: 1916
      order: 3
      base_file: 0C22.txt
    4BD6:
      image_group_id: I2PD16003
      title: ''
      total_pages: 1516
      order: 4
      base_file: 4BD6.txt
    960B:
      image_group_id: I2PD16004
      title: ''
      total_pages: 1690
      order: 5
      base_file: 960B.txt
    '4747':
      image_group_id: I2PD16005
      title: ''
      total_pages: 1582
      order: 6
      base_file: 4747.txt
    E4F8:
      image_group_id: I2PD16006
      title: ''
      total_pages: 1504
      order: 7
      base_file: E4F8.txt
    F7E7:
      image_group_id: I2PD16007
      title: ''
      total_pages: 1600
      order: 8
      base_file: F7E7.txt
    71A9:
      image_group_id: I2PD16008
      title: ''
      total_pages: 1476
      order: 9
      base_file: 71A9.txt
    1B3E:
      image_group_id: I2PD16009
      title: ''
      total_pages: 1134
      order: 10
      base_file: 1B3E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
