id: P010517
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD95727
  title: གངས་ལྗོངས་རིག་བཅུའི་སྙིང་བཅུད་ཆེན་མོ
  author: ''
  volumes:
    2b55406ea2d04c239aaf098371a29f09:
      image_group_id: I2PD16000
      title: ''
      volume_number: 1
      total_pages: 2076
      base_file: v001.txt
    3c6231c4f1534c5a8dc07ef212d7d9eb:
      image_group_id: I2PD16001
      title: ''
      volume_number: 2
      total_pages: 1962
      base_file: v002.txt
    25894df15aca4a52bb183e56f245c87d:
      image_group_id: I2PD16002
      title: ''
      volume_number: 3
      total_pages: 1916
      base_file: v003.txt
    6d11ab1dbae64edba7fda1e65829869d:
      image_group_id: I2PD16003
      title: ''
      volume_number: 4
      total_pages: 1516
      base_file: v004.txt
    f648138c747346b28b01863985cf2cc6:
      image_group_id: I2PD16004
      title: ''
      volume_number: 5
      total_pages: 1690
      base_file: v005.txt
    a3a3b0377c764c8c8b6d1ce54f71f1cd:
      image_group_id: I2PD16005
      title: ''
      volume_number: 6
      total_pages: 1582
      base_file: v006.txt
    aad69444cf4a481daa6741f50d67567a:
      image_group_id: I2PD16006
      title: ''
      volume_number: 7
      total_pages: 1504
      base_file: v007.txt
    eee029c99a4742338e9cab982aaf90dc:
      image_group_id: I2PD16007
      title: ''
      volume_number: 8
      total_pages: 1600
      base_file: v008.txt
    2c752cbbe4d841e6aa1d7035eee4508e:
      image_group_id: I2PD16008
      title: ''
      volume_number: 9
      total_pages: 1476
      base_file: v009.txt
    a82fadd88f934c4ba7ceeac49e8ad340:
      image_group_id: I2PD16009
      title: ''
      volume_number: 10
      total_pages: 1134
      base_file: v010.txt
